### ISSUE TITLE
[os::linux::local::plugin] Mode NTP

### ISSUE THREAD

**Issue by myOmikron** [centreon/centreon-plugins#2141]
## Bug

I'm using the plugin os::linux::local::plugin and wanted to try the ntp check, when I execute the following:
`./centreon_plugins.pl --plugin os::linux::local::plugin --mode ntp`
I'm getting this error:
`UNKNOWN: Command error: Can't exec "ntpq": No such file or directory at /usr/lib/plugins/centreon-plugins/centreon/plugins/misc.pm line 302.`

**Comment by Sims24** [comment]
Hello, 

There was a bug introduced in the last version. Please update your git or your RPM from unstable repository. 

It's fixed now.

Thnaks

**Comment by myOmikron** [comment]
@Sims24 After updating my git the error persists, so it seems there is another bug here
