### ISSUE TITLE
cloud::prometheus::direct::kubernetes::plugin / mode container-status - Filter by reason

### ISSUE THREAD

**Issue by WTFKr0** [centreon/centreon-plugins#2163]
Hi

We try to use the container-status mode for our Openshift cluster
We're facing an issue as some pods are created from batch job (Kind Job) so the state is not ready and the status is teminated with a reason to completed
This containers have a critical status with the default `--critical-status`

The result is
```
Container 'openshift-service-catalog-controller-manager-remover' [pod: openshift-service-catalog-controller-manager-remover-sw56g] state is 'not ready', status is 'terminated_reason' - Restarts count : 0
```

Is there a way with `--critical-status` to check for the reason of the `terminated_reason`
I want containers with a reason to `Completed` have a OK status
This is the raw prometheus response for the reason : 
```
kube_pod_container_status_terminated_reason{container="openshift-service-catalog-controller-manager-remover",endpoint="https-main",instance="10.2.4.20:8443",job="kube-state-metrics",namespace="openshift-service-catalog-removed",pod="openshift-service-catalog-controller-manager-remover-sw56g",prometheus="openshift-monitoring/k8s",reason="Completed",service="kube-state-metrics"}
```

Thanx

**Comment by npeyrussie** [comment]
Hello,

We found that is was possible to filter `--critical-status` by `%{reason}`.  
But we can't figure a way that could take our different cases into account.

To explain, our default filter is : `--critical-status='%{status} !~ /running/ || %{state} !~ /ready/'`

But, configured as is, it makes completed K8S jobs to generate a critical status.  
This is because completed jobs do have : 
- status : terminated_reason
- state : not ready
- reason : Completed

We tried different filters but did not succeed. For example : 
```--critical-status='%{status} !~ /running/ || %{state} !~ /ready/ || (%{status} =~ /terminated_reason/ && %{state} =~ /not ready/ && %{reason} !~ /Completed/)'```

```--critical-status='(%{status} !~ /running|terminated_reason/) || (%{status} =~ /terminated_reason/ && %{reason} !~ /Completed/)'```

How can we configure the filter so that **all** *not ready* and *not running* containers can generate a critical status **except** for those which are in *terminated_reason* status and *Completed* reason ?

**Comment by Sims24** [comment]
Hi @npeyrussie 

Could you give a try to: 

--critical-status='(%{status} !~ /running/ && %{state} !~ /ready/) || (%{status} =~ /terminated_reason/ && %{reason} !~ /Completed/)'

I think it should be OK with this, if not, I'll check deeper at the code level. 

Thanks

**Comment by Sims24** [comment]
Hum, my previous answer won't work. Let me think about it.

**Comment by npeyrussie** [comment]
OK, I confirm :-)
Thanks for your help

**Comment by Sims24** [comment]
Do you think you can provide by mail the result of a check with the --debug option. This way I will be able to test with your data. 

Feel free to send an email to sbomm@centreon.com

**Comment by garnier-quentin** [comment]
Could you test with following version ?
https://github.com/centreon/centreon-plugins/archive/refs/heads/fix-prometheus-direct.zip

**Comment by npeyrussie** [comment]
Hello,
Thank tou for your help.
I will have a look at this as soon as I can.

Do I have to change something in my critical status test ?

**Comment by garnier-quentin** [comment]
I let you test options before. But you can test a stupid status: ```critical-status='1 == 1'```

**Comment by npeyrussie** [comment]
Hello,

Sorry for the delay...
Our Centreon admin let me know that he does not know how to use the provided archive. 
He cannot find the kubernetes plugin inside it.

Could you explain us how to install the fix ?

Regards.

**Comment by garnier-quentin** [comment]
Sent me an email. we could do a session

**Comment by garnier-quentin** [comment]
It should be fixed. if you stil have the issue, comment it

**Comment by Dubouchj** [comment]
@garnier-quentin , I still have the issue with version 5.0.0

![image](https://user-images.githubusercontent.com/33114629/143203031-1a9e82af-3003-473d-8554-543951949775.png)

Is it possible to tell me the parameters that you have to specify? (--critical-container-status and --critical-pod-status )

**Comment by Sims24** [comment]
Hi, 

Is the Plugin up-to-date as well? 

This thread is about the Prometheus / Kubernetes Plugin, not the Kubernetes API. 

Could you please paste your Plugins version: 

`rpm -qa |grep centreon-plugin*`

**Comment by Dubouchj** [comment]
Hi @Sims24 ,

Thanks for your help!

```
--critical-pod-status='%{status} !~ /running|succeeded/i' \
--critical-container-status='%{status} !~ /running|terminated/i' \
```

**Comment by Sims24** [comment]
Thanks for your time! 

We will consider removing the default container critical status because it might be irrelevant (or maybe just update the doc to highlight that). If the Pod container belongs to is healthy, we might want to silent container problems.
