### ISSUE TITLE
plugin=storage::qnap::snmp mode=memory Incorrect values

### ISSUE THREAD

**Issue by Trunxsnot** [centreon/centreon-plugins#2860]
Using the actual memory.pm i get this result:

[root@centreon ~]# /usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --mode=memory --hostname=10.20.2.11 --snmp-community=community --snmp-version=2c --verbose
Use of uninitialized value in numeric lt (<) at /usr/lib64/nagios/plugins/storage/qnap/snmp/mode/memory.pm line 99.
Use of uninitialized value in numeric lt (<) at /usr/lib64/nagios/plugins/storage/qnap/snmp/mode/memory.pm line 99.
OK: Memory total: 785.47 MB used: 784.91 MB (99.93%) free: 573.55 KB (0.07%) | 'memory.usage.bytes'=823032673B;;;0;823619993 'memory.free.bytes'=587320B;;;0;823619993 'memory.usage.percentage'=99.93%;;;0;100

Thats incorrect, so i try to change de OID in memory.pm and put the same in legacy, ex and es:

my $mapping = {
    legacy => {
        ram_total => { oid => '.1.3.6.1.4.1.24681.1.2.2' }, # systemTotalMem
        ram_free  => { oid => '.1.3.6.1.4.1.24681.1.2.3' }  # systemFreeMem
    },
    ex => {
        ram_total => { oid => '.1.3.6.1.4.1.24681.1.2.2' }, # systemTotalMemEX
        ram_free  => { oid => '.1.3.6.1.4.1.24681.1.2.3' }  # systemFreeMemEX
    },
    es => {
        ram_total => { oid => '.1.3.6.1.4.1.24681.1.2.2' }, # es-SystemTotalMem
        ram_free  => { oid => '.1.3.6.1.4.1.24681.1.2.3' }  # es-SystemFreeMem

[root@centreon ~]# /usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --mode=memory --hostname=10.20.2.11 --snmp-community=centreon --snmp-version=2c
OK: Memory total: 7.67 GB used: 2.07 GB (27.01%) free: 5.60 GB (72.99%) | 'memory.usage.bytes'=2224973414B;;;0;8236249907.2 'memory.free.bytes'=6011276492B;;;0;8236249907.2 'memory.usage.percentage'=27.01%;;;0;100

**Comment by garnier-quentin** [comment]
It's already fixed in last version ;)

**Comment by Trunxsnot** [comment]
Still incorrect, 
![image](https://user-images.githubusercontent.com/16260480/121197588-b8125180-c871-11eb-8ec1-913d55c988e0.png)

**Comment by Trunxsnot** [comment]
SNMPv2-SMI::enterprises.24681.1.3.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.3.9.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.3.9.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.3.9.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.24681.1.3.9.1.2.1 = STRING: "eth0"
SNMPv2-SMI::enterprises.24681.1.3.9.1.2.2 = STRING: "eth1"
SNMPv2-SMI::enterprises.24681.1.3.9.1.2.3 = STRING: "eth2"
SNMPv2-SMI::enterprises.24681.1.3.9.1.2.4 = STRING: "eth3"
SNMPv2-SMI::enterprises.24681.1.3.9.1.3.1 = Counter32: 307673824
SNMPv2-SMI::enterprises.24681.1.3.9.1.3.2 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.3.3 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.3.4 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.4.1 = Counter32: 866019995
SNMPv2-SMI::enterprises.24681.1.3.9.1.4.2 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.4.3 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.4.4 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.5.1 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.5.2 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.5.3 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.9.1.5.4 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.3.11.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.3.11.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.3.11.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.3.11.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.24681.1.3.11.1.2.1 = STRING: "HDD1"
SNMPv2-SMI::enterprises.24681.1.3.11.1.2.2 = STRING: "HDD2"
SNMPv2-SMI::enterprises.24681.1.3.11.1.2.3 = STRING: "HDD3"
SNMPv2-SMI::enterprises.24681.1.3.11.1.2.4 = STRING: "HDD4"
SNMPv2-SMI::enterprises.24681.1.3.11.1.3.1 = INTEGER: 27
SNMPv2-SMI::enterprises.24681.1.3.11.1.3.2 = INTEGER: 27
SNMPv2-SMI::enterprises.24681.1.3.11.1.3.3 = INTEGER: 27
SNMPv2-SMI::enterprises.24681.1.3.11.1.3.4 = INTEGER: 28
SNMPv2-SMI::enterprises.24681.1.3.11.1.4.1 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.3.11.1.4.2 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.3.11.1.4.3 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.3.11.1.4.4 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.3.11.1.5.1 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.3.11.1.5.2 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.3.11.1.5.3 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.3.11.1.5.4 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.3.11.1.6.1 = Counter64: 2000398934016
SNMPv2-SMI::enterprises.24681.1.3.11.1.6.2 = Counter64: 2000398934016
SNMPv2-SMI::enterprises.24681.1.3.11.1.6.3 = Counter64: 2000398934016
SNMPv2-SMI::enterprises.24681.1.3.11.1.6.4 = Counter64: 2000398934016
SNMPv2-SMI::enterprises.24681.1.3.11.1.7.1 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.3.11.1.7.2 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.3.11.1.7.3 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.3.11.1.7.4 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.3.15.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.3.15.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.3.15.1.2.1 = STRING: "System FAN 1"
SNMPv2-SMI::enterprises.24681.1.3.15.1.2.2 = STRING: "System FAN 2"
SNMPv2-SMI::enterprises.24681.1.3.15.1.3.1 = INTEGER: 6024
SNMPv2-SMI::enterprises.24681.1.3.15.1.3.2 = INTEGER: 5836
SNMPv2-SMI::enterprises.24681.1.3.17.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.3.17.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.3.17.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.3.17.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.24681.1.3.17.1.2.1 = STRING: "[Volume FILER]"
SNMPv2-SMI::enterprises.24681.1.3.17.1.2.2 = STRING: "[Single Disk Volume:  Host Drive: 2]"
SNMPv2-SMI::enterprises.24681.1.3.17.1.2.3 = STRING: "[Single Disk Volume:  EXDR#33 Drive: 2]"
SNMPv2-SMI::enterprises.24681.1.3.17.1.2.4 = STRING: "[Single Disk Volume:  EXDR#33 Drive: 4]"
SNMPv2-SMI::enterprises.24681.1.3.17.1.3.1 = STRING: "EXT4"
SNMPv2-SMI::enterprises.24681.1.3.17.1.3.2 = STRING: "Unknown"
SNMPv2-SMI::enterprises.24681.1.3.17.1.3.3 = STRING: "Unknown"
SNMPv2-SMI::enterprises.24681.1.3.17.1.3.4 = STRING: "Unknown"
SNMPv2-SMI::enterprises.24681.1.3.17.1.4.1 = Counter64: 3787164768
SNMPv2-SMI::enterprises.24681.1.3.17.1.4.2 = Counter64: 0
SNMPv2-SMI::enterprises.24681.1.3.17.1.4.3 = Counter64: 3906982908
SNMPv2-SMI::enterprises.24681.1.3.17.1.4.4 = Counter64: 3906975844
SNMPv2-SMI::enterprises.24681.1.3.17.1.5.1 = Counter64: 728353152
SNMPv2-SMI::enterprises.24681.1.3.17.1.5.2 = Counter64: 0
SNMPv2-SMI::enterprises.24681.1.3.17.1.5.3 = Counter64: 399350564
SNMPv2-SMI::enterprises.24681.1.3.17.1.5.4 = Counter64: 891088964
SNMPv2-SMI::enterprises.24681.1.3.17.1.6.1 = STRING: "Ready"
SNMPv2-SMI::enterprises.24681.1.3.17.1.6.2 = STRING: "Global Spare"
SNMPv2-SMI::enterprises.24681.1.3.17.1.6.3 = STRING: "Ready"
SNMPv2-SMI::enterprises.24681.1.3.17.1.6.4 = STRING: "Ready"

**Comment by Trunxsnot** [comment]
SNMPv2-SMI::enterprises.24681.1.2.1.0 = STRING: "0.40 %"
SNMPv2-SMI::enterprises.24681.1.2.9.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.2.9.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.2.9.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.2.9.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.24681.1.2.9.1.2.1 = STRING: "eth0"
SNMPv2-SMI::enterprises.24681.1.2.9.1.2.2 = STRING: "eth1"
SNMPv2-SMI::enterprises.24681.1.2.9.1.2.3 = STRING: "eth2"
SNMPv2-SMI::enterprises.24681.1.2.9.1.2.4 = STRING: "eth3"
SNMPv2-SMI::enterprises.24681.1.2.9.1.3.1 = Counter32: 307674450
SNMPv2-SMI::enterprises.24681.1.2.9.1.3.2 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.3.3 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.3.4 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.4.1 = Counter32: 866020507
SNMPv2-SMI::enterprises.24681.1.2.9.1.4.2 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.4.3 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.4.4 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.5.1 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.5.2 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.5.3 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.9.1.5.4 = Counter32: 0
SNMPv2-SMI::enterprises.24681.1.2.11.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.2.11.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.2.11.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.2.11.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.24681.1.2.11.1.2.1 = STRING: "HDD1"
SNMPv2-SMI::enterprises.24681.1.2.11.1.2.2 = STRING: "HDD2"
SNMPv2-SMI::enterprises.24681.1.2.11.1.2.3 = STRING: "HDD3"
SNMPv2-SMI::enterprises.24681.1.2.11.1.2.4 = STRING: "HDD4"
SNMPv2-SMI::enterprises.24681.1.2.11.1.3.1 = STRING: "27 C/80 F"
SNMPv2-SMI::enterprises.24681.1.2.11.1.3.2 = STRING: "27 C/80 F"
SNMPv2-SMI::enterprises.24681.1.2.11.1.3.3 = STRING: "28 C/82 F"
SNMPv2-SMI::enterprises.24681.1.2.11.1.3.4 = STRING: "28 C/82 F"
SNMPv2-SMI::enterprises.24681.1.2.11.1.4.1 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.2.11.1.4.2 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.2.11.1.4.3 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.2.11.1.4.4 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.2.11.1.5.1 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.2.11.1.5.2 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.2.11.1.5.3 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.2.11.1.5.4 = STRING: "ST2000VN004-2E4164"
SNMPv2-SMI::enterprises.24681.1.2.11.1.6.1 = STRING: "1.82 TB"
SNMPv2-SMI::enterprises.24681.1.2.11.1.6.2 = STRING: "1.82 TB"
SNMPv2-SMI::enterprises.24681.1.2.11.1.6.3 = STRING: "1.82 TB"
SNMPv2-SMI::enterprises.24681.1.2.11.1.6.4 = STRING: "1.82 TB"
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.1 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.2 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.3 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.4 = STRING: "GOOD"
SNMPv2-SMI::enterprises.24681.1.2.15.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.2.15.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.2.15.1.2.1 = STRING: "System FAN 1"
SNMPv2-SMI::enterprises.24681.1.2.15.1.2.2 = STRING: "System FAN 2"
SNMPv2-SMI::enterprises.24681.1.2.15.1.3.1 = STRING: "5976 RPM"
SNMPv2-SMI::enterprises.24681.1.2.15.1.3.2 = STRING: "5882 RPM"

**Comment by garnier-quentin** [comment]
Shitty snmp agent... Could you try the command:
```
snmpget -c community -v 2c ip_qnap .1.3.6.1.4.1.24681.1.2.2.0 .1.3.6.1.4.1.24681.1.2.3.0 .1.3.6.1.4.1.24681.1.3.2.0 .1.3.6.1.4.1.24681.1.3.3.0 .1.3.6.1.4.1.24681.2.2.2.0 .1.3.6.1.4.1.24681.2.2.3.0
```

**Comment by Trunxsnot** [comment]
SNMPv2-SMI::enterprises.24681.1.2.2.0 = STRING: "7854.7 MB"
SNMPv2-SMI::enterprises.24681.1.2.3.0 = STRING: "5751.0 MB"
SNMPv2-SMI::enterprises.24681.1.3.2.0 = Counter64: 8236199936
SNMPv2-SMI::enterprises.24681.1.3.3.0 = Counter64: 5889032
SNMPv2-SMI::enterprises.24681.2.2.2.0 = No Such Object available on this agent at this OID
SNMPv2-SMI::enterprises.24681.2.2.3.0 = No Such Object available on this agent at this OID

**Comment by garnier-quentin** [comment]
It's an issue with qnap... the free is very low:  SNMPv2-SMI::enterprises.24681.1.3.3.0 = Counter64: 5889032

**Comment by UrBnW** [comment]
Yes, seems like a unit issue, same behavior here :
```
$ snmpwalk ... .1.3.6.1.4.1.24681.1.2.2 
.1.3.6.1.4.1.24681.1.2.2.0 = STRING: "8167.0 MB"
$ snmpwalk ... .1.3.6.1.4.1.24681.1.3.2
.1.3.6.1.4.1.24681.1.3.2.0 = Counter64: 8563720192

$ snmpwalk ... .1.3.6.1.4.1.24681.1.2.3
.1.3.6.1.4.1.24681.1.2.3.0 = STRING: "6519.2 MB"
$ snmpwalk ... .1.3.6.1.4.1.24681.1.3.3
.1.3.6.1.4.1.24681.1.3.3.0 = Counter64: 6679168
```

**Comment by UrBnW** [comment]
Yes, seems like a unit issue, same behavior here :
```
$ snmpwalk ... .1.3.6.1.4.1.24681.1.2.2 
.1.3.6.1.4.1.24681.1.2.2.0 = STRING: "8167.0 MB"
$ snmpwalk ... .1.3.6.1.4.1.24681.1.3.2
.1.3.6.1.4.1.24681.1.3.2.0 = Counter64: 8563720192

$ snmpwalk ... .1.3.6.1.4.1.24681.1.2.3
.1.3.6.1.4.1.24681.1.2.3.0 = STRING: "6519.2 MB"
$ snmpwalk ... .1.3.6.1.4.1.24681.1.3.3
.1.3.6.1.4.1.24681.1.3.3.0 = Counter64: 6679168
```

And here what `storage` standard mode returns :
```
'used_Physical memory' = 3136978944B;;;0; 8563720192
'used_Swap space'      =   46563328B;;;0;25131384832
'used_Virtual memory'  = 3183542272B;;;0;33695105024
'used_Memory buffers'  =  769523712B;;;0; 8563720192
'used_Cached memory'   = 1048936448B;;;0; 1048936448
'used_Shared memory'   =  404684800B;;;0;  404684800
```

**Comment by UrBnW** [comment]
Yes, seems like a unit issue, same behavior here :
```
.1.3.6.1.4.1.24681.1.2.2.0 = STRING: "8167.0 MB"
.1.3.6.1.4.1.24681.1.3.2.0 = Counter64: 8563720192
.1.3.6.1.4.1.24681.1.2.3.0 = STRING: "6519.2 MB"
.1.3.6.1.4.1.24681.1.3.3.0 = Counter64: 6679168
```

Here's the `qnap` branch :
```
```
.1.3.6.1.4.1.55062.1.12.13.0 = Counter64: 8563720192
.1.3.6.1.4.1.55062.1.12.14.0 = Counter64: 6685920
.1.3.6.1.4.1.55062.1.12.15.0 = Counter64: 6482460672
.1.3.6.1.4.1.55062.1.12.16.0 = Counter64: 8563720192
.1.3.6.1.4.1.55062.1.12.17.0 = Counter64: 878247936
.1.3.6.1.4.1.55062.1.12.18.0 = Counter64: 781975552
```

And here what `storage` standard mode returns :
```
'used_Physical memory' = 3136978944B;;;0; 8563720192
'used_Swap space'      =   46563328B;;;0;25131384832
'used_Virtual memory'  = 3183542272B;;;0;33695105024
'used_Memory buffers'  =  769523712B;;;0; 8563720192
'used_Cached memory'   = 1048936448B;;;0; 1048936448
'used_Shared memory'   =  404684800B;;;0;  404684800
```

**Comment by UrBnW** [comment]
Let's introduce a `--legacy` switch in the `memory` mode @garnier-quentin ?
So that we can get rid of these crappy EX/ES counters until Qnap fixes the issue ?

**Comment by garnier-quentin** [comment]
You want your legacy :) I can add an option to force it

**Comment by UrBnW** [comment]
;) on `memory` mode only would be enough, as a temporary workaround 👍
