### ISSUE TITLE
[apps::monitoring::netdata::restapi::plugin] get-chart apps.processes strange value

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon-plugins#3392]
Hello !
I have a strange behavior with the netdata plugin.
I wanted to monitor specific process of my hosts, so I used the get-chart mode and filter on my specific process.

For example on SSH it works great:
`
[centreon-engine@xxx plugins]$ ./centreon_plugins.pl --plugin=apps::monitoring::netdata::restapi::plugin --mode=get-chart --hostname=lxxxxx --proto=https --chart-name=apps.processes  --filter-metric=ssh --debug
OK: Metric 'ssh_average' value is 14.00 processes | 'ssh_average'=14processes;;;;
`
This is the data associate:
`{
 "labels": ["time", "ssh"],
    "data":
 [
      [ 1641831300, 14]
  ]
}
`

And with ceph:
`[centreon-engine@xxxxxxx plugins]$ ./centreon_plugins.pl --plugin=apps::monitoring::netdata::restapi::plugin --mode=get-chart --hostname=xxxxxxxx --proto=https --chart-name=apps.processes  --filter-metric=ceph --debug
OK: Metric 'ceph_average' value is 1641831300.00 processes | 'ceph_average'=1641831300processes;;;;
`
This is the data associate:
`{
 "labels": ["time", "ceph"],
    "data":
 [
      [ 1641831300, 1]
  ]
}
`
It seems that for some of string the plugin associate the number with the time and not the value.

**Comment by garnier-quentin** [comment]
Could you provide the --debug result ?

**Comment by mullergg** [comment]
Please find it in attachment, I provide one wit ssh who works and one with ceph who don't work.
I thought the json data was enough to diagnose.
[debug_plugin_netdata.txt](https://github.com/centreon/centreon-plugins/files/7844766/debug_plugin_netdata.txt)

**Comment by garnier-quentin** [comment]
You can test with last git version. It should be fixed

**Comment by mullergg** [comment]
Hello ! 
I tried 20211215 version and I still have the issue.

**Comment by garnier-quentin** [comment]
It's last git version. It's not yet released .

**Comment by mullergg** [comment]
My bad, I will wait the  next release.

**Comment by mullergg** [comment]
I had time to test with the current master.
It works ! Thank you
Do you know in which release it will be fix ?
